### ISSUE TITLE
Fails with multiple documents

### ISSUE THREAD

**Issue by sstarcher** [weaveworks/kubediff#13]
If a yaml file contains multiple definitions the code errors.

Example:
```
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: readonly-binding
subjects:
  - kind: Group
    name: readonly
roleRef:
  kind: ClusterRole
  name: readonly-role
  apiVersion: rbac.authorization.k8s.io/v1alpha1
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: system-admin-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: system
roleRef:
  kind: ClusterRole
  name: admin-role
  apiVersion: rbac.authorization.k8s.io/v1alpha1
```

```
Traceback (most recent call last):
  File "kubediff/kubediff", line 40, in <module>
    main()
  File "kubediff/kubediff", line 34, in main
    failed = check_files(args, printer, options.kubeconfig)
  File "kubediff/kubedifflib/_diff.py", line 137, in check_files
    differences += check_file(printer, path, kubeconfig=kubeconfig)
  File "kubediff/kubedifflib/_diff.py", line 80, in check_file
    expected = yaml.load(stream)
  File "/usr/local/lib/python2.7/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/local/lib/python2.7/site-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python2.7/site-packages/yaml/composer.py", line 43, in get_single_node
    event.start_mark)
yaml.composer.ComposerError: expected a single document in the stream
  in "workspace/charts/x/manifests/x.yaml", line 1, column 1
but found another document
  in "workspace/charts/x/manifests/x.yaml", line 10, column 1
```

**Comment by tomwilkie** [comment]
Hi Shane, your right this won't work with multiple docs. Should be an easy
fix.
