### ISSUE TITLE
TypeError: not enough arguments for format string

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/kubediff#30]
```
## monitoring/prometheus-config (ConfigMap)

Traceback (most recent call last):
  File "/kubediff", line 40, in <module>
    main()
  File "/kubediff", line 34, in main
    failed = check_files(args, printer, options.kubeconfig)
  File "/usr/lib/python2.7/site-packages/kubedifflib/_diff.py", line 191, in check_files
    differences += check_file(printer, path, kubeconfig=kubeconfig)
  File "/usr/lib/python2.7/site-packages/kubedifflib/_diff.py", line 122, in check_file
    printer.diff(path, difference)
  File "/usr/lib/python2.7/site-packages/kubedifflib/_diff.py", line 158, in diff
    self._write(difference.to_text())
  File "/usr/lib/python2.7/site-packages/kubedifflib/_diff.py", line 145, in _write
    self._stream.write(msg % args)
TypeError: not enough arguments for format string
```

**Comment by tomwilkie** [comment]
I stuck https://github.com/weaveworks/kubediff/commit/b7552093b705401d9b33f3ef99865403e35a4599 as a quick attempt to fix this for a demo.
