### ISSUE TITLE
TypeError on SealedSecret

### ISSUE THREAD

**Issue by bboreham** [weaveworks/kubediff#80]
Reported in PR #78 

error below for e.g. `SealedSecret.v1alpha1.bitnami.com`

```
Traceback (most recent call last):
  File "/Users/po/src/kubediff/kubediff", line 48, in <module>
    main()
  File "/Users/po/src/kubediff/kubediff", line 42, in main
    failed = check_files(args, printer, config)
  File "/Users/po/src/kubediff/kubedifflib/_diff.py", line 246, in check_files
    differences += check_file(printer, path, config)
  File "/Users/po/src/kubediff/kubedifflib/_diff.py", line 174, in check_file
    printer.diff(path, difference)
  File "/Users/po/src/kubediff/kubedifflib/_diff.py", line 214, in diff
    self._write('%s', difference.to_text(self._current.kind))
  File "/Users/po/src/kubediff/kubedifflib/_diff.py", line 35, in to_text
    message = self.message % ((len(self.args[0]) * '*'), (len(self.args[1]) * '*'))
TypeError: object of type 'NoneType' has no len()
```

**Comment by awh** [comment]
I believe this particular exception happens because when you seal a secret with `kubeseal`, the generated manifest contains this:

```
metadata:
    creationTimestamp: null
```

when the fix in #78 is applied, `kubediff` correctly reports the error:

```
## some-namespace/some-sealed-secret (SealedSecret.v1alpha1.bitnami.com)

.metadata.creationTimestamp: 'None' != '2019-02-07 19:14:11'
```

Obviously this can happen to a `Secret` too.
